#!/bin/bash

# make-jpgvideo
# Given a directory with jpegs, make a
# time-lapse of all the motion captured.

if [ -n "$1" ]; then
	export DIR="$1"
else
	echo "Define a directory as first arguement..."
	exit 1
fi

if [ -n "$2" ]; then
	export OUTFILE="$2"
else
	echo "Define an output file as second arguement..."
	exit 1
fi

/usr/bin/mencoder "mf://$DIR/*.jpg" -mf fps=10 -o "$OUTFILE" -ovc lavc -lavcopts vcodec=msmpeg4v2:vbitrate=800
