#!/usr/bin/env python

"""
Copies frames into a sequence.
"""

import sys
import shutil

__author__ = "Paul Kilgo"


def main():
  if len(sys.argv) < 3:
    print "Usage: %s output.ext [input1 [input2 ...]]"    
    sys.exit(1)

  output = sys.argv[1]
  frames = sys.argv[2:]

  base, ext = output.rsplit(".", 1)
  i = 1
  for frame in frames:
    frame_no = "%04d" % i
    dst = "%s.%s.%s" % (base, frame_no, ext)
    shutil.copy(frame, dst)
    i += 1

if __name__ == "__main__":
  main()
