#!/usr/bin/env python3

import sys
import os

SETS_SEARCH = [
  "sets",
  ".sets",
  os.envrion["HOME"] + "sets",
  os.envrion["HOME"] + ".sets",

]

SETS_DIRECTORY = os.environ["HOME"] + "/.sets"

OP_INTERSECT = 1
OP_UNION = 2
OP_DIFFERENCE = 3

class Domain:

  UNIVERSE_FILE = 'all'
  
  def __init__(self, domainPath):
    self._path = domainPath
    self._universe = None
    self._subsets = None
    self._initialize()

  def universe(self):
    return set(self._universe)

  def subset(self, name):
    return self._subsets[name]

  def _initialize(self):
    self._universe = self._toset(self._childpath(Domain.UNIVERSE_FILE))
    self._subsets = dict()

    for path in os.listdir(self._path):
      if path is Domain.UNIVERSE_FILE: continue
      fullpath = self._childpath(path)
      if os.path.isfile(fullpath):
        self._subsets[path] = self._toset(fullpath)

  def __iter__(self):
    return self._universe.__iter__()

  def _childpath(self, path):
    return os.path.join(self._path, path)

  def _toset(self, path):
    out = set()
    with open(path) as fp:
      for line in fp:
        out |= set([line.strip()])
    return out

def dispatch(domain, current, item):
  if current == None:
    current = domain.universe()

  if item[0] == "@":
    item = item[1:]
    current |= domain.subset(item)
  elif item[0] == "-":
    item = item[1:]
    current -= domain.subset(item)
  else:
    current &= domain.subset(item)

  return current


def printUsage():
  print("Usage: %s <set> [set1 [set2]]" % os.path.basename(sys.argv[0]))

def main():
  global SETS_DIRECTORY

  if len(sys.argv) < 2:
    printUsage()
    sys.exit(1)
  
  universeName = sys.argv[1]
  ops = sys.argv[2:]

  domain = Domain(os.path.join(SETS_DIRECTORY, universeName))
  current = domain.universe()

  for op in ops:
    current = dispatch(domain, current, op)

  for item in current:
    print(item)

if __name__ == "__main__":
  main()
