#!/usr/bin/env python

import sys
import cv2
import numpy as np

def printUsage():
  print "Usage: %s <from> <to>" % sys.argv[0]

def texturize(im):
  (width, height, depth) = im.shape

  rightHalf = np.zeros((width, height, depth))
  bottomHalf = np.zeros((2*width, height, depth))
  resize = np.append(im, rightHalf, 0)
  resize = np.append(resize, bottomHalf, 1)

  out = np.zeros((width*2, height*2, depth))

  out = cv2.add(out, resize)
  out = cv2.add(out, cv2.flip(resize, 0))
  out = cv2.add(out, cv2.flip(resize, 1))
  out = cv2.add(out, cv2.flip(resize, -1))
  
  return out

def main():
  if len(sys.argv) != 3:
    printUsage()
    sys.exit(1)

  filein = sys.argv[1]
  fileout = sys.argv[2]

  im = cv2.imread(filein)
  im = texturize(im)
  cv2.imwrite(fileout, im)

if __name__ == "__main__":
  main()
  
